theme: jekyll-theme-minimal
title: HINDI
description: [A short description of your site's purpose]
logo: ./image/avatar.jpg
show_downloads: "true"
google_analytics: [Your Google Analytics tracking ID]
